spring:
  datasource:
    url: jdbc:mysql://localhost:13306/crud_spring_boot_3_test
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}