spring:
  datasource:
    url: jdbc:mysql://localhost:13306/crud_spring_boot_3
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false